# Generated by Django 5.2.8 on 2025-11-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Телефон")),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("processed", models.BooleanField(default=False, verbose_name="Обработано")),
            ],
            options={
                "verbose_name": "Запрос на контакт",
                "verbose_name_plural": "Запросы на контакт",
                "ordering": ["-created_at"],
            },
        ),
    ]
